# Generated by Django 3.2.5 on 2021-11-11 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='prefecture_id',
            field=models.ForeignKey(max_length=11, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.prefectures'),
        ),
    ]
