# Generated by Django 3.2.5 on 2021-11-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Live stream event'), (2, 'Office event')])),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_private', models.IntegerField(choices=[(0, 'Not private'), (1, 'Private')], default=1)),
                ('private_key', models.CharField(max_length=255, null=True)),
                ('is_archived', models.IntegerField(choices=[(0, 'Not archived'), (1, 'Archived')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
