# Generated by Django 3.2.9 on 2021-11-10 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Live stream event'), (2, 'Office event')])),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_private', models.IntegerField(choices=[(0, 'Not private'), (1, 'Private')], default=1)),
                ('private_key', models.CharField(max_length=255, null=True)),
                ('is_archived', models.IntegerField(choices=[(0, 'Not archived'), (1, 'Archived')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clients')),
            ],
        ),
    ]
