# Generated by Django 3.2.5 on 2021-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
