# Generated by Django 3.2.5 on 2021-11-17 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_authorized_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_authorized_user',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eauu', to='event.event'),
        ),
    ]
