# Generated by Django 3.2.5 on 2021-11-18 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_alter_event_authorized_user_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('streaming_method', models.SmallIntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('start_datetime', models.DateTimeField(auto_now_add=True)),
                ('end_datetime', models.DateTimeField(auto_now_add=True)),
                ('capacity', models.IntegerField(null=True)),
                ('ticket_available_flag', models.SmallIntegerField(choices=[(0, 'Not available'), (1, 'Available')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('points_required', models.DecimalField(decimal_places=0, max_digits=15, null=True)),
                ('expiration_datetime', models.DateTimeField(auto_now_add=True)),
                ('drawing_flag', models.SmallIntegerField(choices=[(0, 'No drawing'), (1, 'By drawing')], default=1)),
                ('drawing_application_deadline', models.DateTimeField(auto_now_add=True, null=True)),
                ('drawing_status', models.SmallIntegerField(choices=[(0, 'Drawing preiod'), (1, ' Purchase method')], default=1)),
                ('stamp_available_flag', models.SmallIntegerField(choices=[(0, 'Not available'), (1, 'Available')], default=1)),
                ('max_number_of_ticket', models.IntegerField()),
                ('number_of_issued_tickets', models.IntegerField()),
                ('is_seat_id_assigned', models.SmallIntegerField(choices=[(0, 'Not assigned'), (1, 'Assigned')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.performance')),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_elected', models.SmallIntegerField(choices=[(0, 'Not elected'), (1, 'Elected')], default=1)),
                ('is_purchased', models.SmallIntegerField(choices=[(0, 'Not purchased'), (1, 'Purchased')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketmodel', to='event.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_drawing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
