# Generated by Django 3.2.5 on 2021-11-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_drawing_performance_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='streaming_method',
            field=models.SmallIntegerField(choices=[(1, 'APP'), (2, 'OBS')], null=True),
        ),
    ]
