# Generated by Django 3.2.5 on 2021-11-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_performance_streaming_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='drawing_application_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
