# Generated by Django 3.2.5 on 2021-11-16 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_point',
            fields=[
                ('user_point_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdrawal')], default=1)),
                ('deposit_reason', models.IntegerField(choices=[(1, 'Purchase')], null=True)),
                ('withdrawal_reason', models.IntegerField(choices=[(1, 'Exchange for a gift'), (2, 'Exchange for a ticket')], null=True)),
                ('points', models.DecimalField(decimal_places=0, max_digits=15)),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('points_balance', models.DecimalField(decimal_places=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
