# Generated by Django 3.2.5 on 2021-12-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211207_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Đang chờ phê duyệt'), (1, 'Chờ lấy hàng'), (2, 'Đang giao'), (3, 'Đã giao đến người dùng')], default=0),
        ),
    ]
