# Generated by Django 3.2.5 on 2021-11-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apple_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='facebook_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_kana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name_kanji',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_kana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name_kanji',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='remember_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='twitter_id',
        ),
    ]
