# Generated by Django 3.2.5 on 2021-11-12 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_client_id'),
        ('user', '0004_auto_20211112_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_paths',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_img', to='event.event'),
        ),
    ]
