# Generated by Django 3.2.5 on 2021-11-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_image_paths_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_paths',
            name='image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
