# Generated by Django 3.2.5 on 2021-11-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproductelectric',
            name='storage',
            field=models.IntegerField(blank=True, choices=[(32, '32G'), (64, '64G'), (128, '128G'), (256, '256G'), (512, '512G'), (1024, '1TB')], null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='products.Tag'),
        ),
    ]
