# Generated by Django 3.2.5 on 2021-12-01 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_old',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
