# Generated by Django 3.2.5 on 2021-12-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_price_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='des',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
